apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-app
  name: demo-app
  namespace: deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-app
    spec:
      containers:
      - image: medanouar/vuejs-demo-app:v1
        name: vuejs-demo-app
        resources: {}
status: {}
